name: Deploy Parking Project

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Logika 'Clean Existing' dari Jenkins Anda
            # Hapus container lama jika ada
            docker stop parking || true
            docker rm parking || true
            docker rmi dentowahyu/parking:latest || true

            # Masuk ke folder project (Opsional jika build di server)
            # Atau tarik image jika Anda build di GitHub
            
            # Rebuild dan Run (Logika Build Docker Anda)
            cd /path/to/your/project
            docker build -t dentowahyu/jam:latest .
            docker run -d -p 8070:80 --name jam dentowahyu/jam:latest